### ISSUE TITLE
Исключить папку `/docs/` из триггеров Github Actions

### ISSUE THREAD

**Issue by petrmaslov** [u473t8/learning-app#13]
Пример:

```yaml
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
```
